# Generated by Django 5.2.7 on 2025-10-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adnor_Markting', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SC', 'Sports-Cars'), ('EVs', 'Luxury-Electric-Vehicles')], max_length=3),
        ),
    ]
